CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE USER root WITH PASSWORD 'root' CREATEDB;
SELECT 'CREATE DATABASE outecho OWNER "root" ENCODING "UTF8" LC_COLLATE "en_US.utf8" LC_CTYPE "en_US.utf8" TABLESPACE pg_default CONNECTION LIMIT-1'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'outecho')\gexec
ALTER USER root SUPERUSER;
